### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by hatchan** [wercker/go-wercker-api#1]
High priority
- [x] #6 Finalize on method interface
- [x] #2 Merge config overrides in makeRequest
- [x] #7 Implement tokensService
- [x] #8 Implement deploysService
- [x] #3 Add wercker.yml
- [x] #4 Cleanup golint issues
- [x] #12 Implement solution for paging 
- [x] #13 Token cli argument should be used
- [x] #15 Rename Config.Creds to Config.Credentials

Low priority
- [ ] #11 Provide better way to debug problems
- [ ] #5 Ability to change env var key for EnvProvider
- [x] #14 explorer should return a non zero return value when error occured
- [x] #10 Add force anonymous flag to explorer
- [x] #9 Rename cmd/api to explorer (or something like that)
